substitutions:
  device_name: voice-assistant
  friendly_name: ESP32-S3-BOX-3B Voice Assistant
  backend_ip: "${BACKEND_IP}"  # Replace with your Ubuntu host IP (get via: hostname -I)

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.1

esp32:
  board: esp32s3box
  variant: ESP32S3
  flash_size: 16MB

# Enable logging
logger:
  level: DEBUG

# Enable OTA updates
ota:
  - platform: esphome

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 10min
  fast_connect: true

# API configuration for ESPHome
api:
  services:
    - service: voice_assistant_set_listening
      variables:
        enabled: bool

# Voice Assistant Component
# Configure to use the Wyoming protocol to communicate with your backend server
voice_assistant:
  microphone: mic
  speaker: speaker
  use_wake_word: false

# Microphone - ESP32-S3-BOX-3B has built-in I2S microphone
microphone:
  - platform: i2s_audio
    id: mic
    i2s_din_pin: GPIO46
    adc_type: external
    adc_pin: GPIO0

# Speaker - ESP32-S3-BOX-3B has built-in speaker
speaker:
  - platform: i2s_audio
    id: speaker
    i2s_dout_pin: GPIO8
    dac_type: external
    mode: mono

# Display - ESP32-S3-BOX-3B has a built-in screen
display:
  - platform: ili9341
    id: display
    cs_pin: GPIO39
    dc_pin: GPIO40
    sdi_pin: GPIO35
    sdo_pin: GPIO37
    scl_pin: GPIO36
    led_pin: GPIO38

# Wyoming Protocol Service
# This component connects to the Wyoming server running on your Ubuntu host
extern_component:
  source: github://esphome/esphome-external-components
  components:
    - wyoming

# Wyoming client configuration
# Connects to the Python Wyoming server for audio processing
wyoming:
  host: ${backend_ip}
  port: 10700
