# ESP32-S3-BOX-3B Voice Assistant Configuration
# Integrates with Wyoming voice assistant protocol
#
# Setup Instructions:
# 1. Get your Ubuntu host IP: hostname -I
# 2. Replace backend_ip placeholder below
# 3. Create secrets.yaml with wifi_ssid and wifi_password

packages:
  # Use official ESP32-S3-BOX-3 package for hardware support
  esp32_s3_box_3: github://esphome/esphome/esp32_s3_box_3.yaml

substitutions:
  device_name: voice-assistant
  friendly_name: ESP32-S3-BOX-3B Voice Assistant
  backend_ip: "192.168.1.100"  # PLACEHOLDER: Replace with actual IP from hostname -I

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.1

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 10min
  fast_connect: true

# Enable logging
logger:
  level: INFO

# Enable OTA (Over-The-Air) updates
ota:
  - platform: esphome

# ESPHome API for integration and services
api:
  services:
    - service: voice_assistant_set_listening
      variables:
        enabled: bool

# Voice Assistant Component
# Processes audio from microphone and sends to Wyoming server
voice_assistant:
  microphone: mic
  speaker: speaker
  use_wake_word: false

# Wyoming Protocol Connection
# Connects to the Python Wyoming server for intelligent voice processing
external_components:
  - source: github://esphome/esphome-external-components
    components:
      - wyoming

wyoming:
  host: ${backend_ip}
  port: 10700
